#!/usr/bin/env bash

set -o nounset

GREEN="\e[32m"
LIGHTBLUE="\e[94m"
ENDCOLOR="\e[0m"

#

pushd /etc/nixos/

	wget https://git.sovransystems.com/Sovran_Systems/Sovran_SystemsOS/raw/branch/main/for_new_sovran_pros/flake.nix

	chown root:root /etc/nixos/ -R
	
	chmod 770 /etc/nixos/ -R

popd

#

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/home/ /home

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/var/lib/www/ /var/lib/www

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/var/lib/domains/ /var/lib/domains

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/var/lib/nextcloudaddition/ /var/lib/nextcloudaddition

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/var/lib/njalla/ /var/lib/njalla

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/var/lib/external_ip/ /var/lib/external_ip

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/var/lib/secrets/ /var/lib/secrets

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/var/lib/agenix-secrets/ /var/lib/agenix-secrets

rsync -av -e "ssh -i /root/factory_login_install" root@192.168.0.103:/root/.ssh/agenix/ /root/.ssh/agenix

#

echo -n $(pwgen -s 17 -1) > /var/lib/secrets/nextclouddb 
echo -n $(pwgen -s 17 -1) > /var/lib/secrets/wordpressdb 
echo -n $(pwgen -s 17 -1) > /var/lib/secrets/matrixdb
echo -n $(pwgen -s 17 -1) > /var/lib/secrets/turn
echo -n $(pwgen -s 17 -1) > /var/lib/secrets/matrix_reg_secret
echo -n $(pwgen -s 17 -1) > /var/lib/secrets/main
echo -n $(pwgen -s 17 -1) > /var/lib/secrets/onlyofficejwtSecretFile
echo -n ADMIN_TOKEN=$(openssl rand -base64 48
) > /var/lib/secrets/vaultwarden/vaultwarden.env

#

rm -rf /var/lib/agenix-secrets/nextclouddb.age
rm -rf /var/lib/agenix-secrets/wordpressdb.age
rm -rf /var/lib/agenix-secrets/turn.age
rm -rf /var/lib/agenix-secrets/matrixdb.age
rm -rf /var/lib/agenix-secrets/matrix_reg_secret.age

pushd /var/lib/agenix-secrets/

  echo -n $(cat /var/lib/secrets/wordpressdb) | EDITOR='cp /dev/stdin' nix run github:ryantm/agenix -- -e wordpressdb.age -i /root/.ssh/agenix/agenix-secret-keys

  echo -n $(cat /var/lib/secrets/nextclouddb) | EDITOR='cp /dev/stdin' nix run github:ryantm/agenix -- -e nextclouddb.age -i /root/.ssh/agenix/agenix-secret-keys

  echo -n $(cat /var/lib/secrets/matrixdb) | EDITOR='cp /dev/stdin' nix run github:ryantm/agenix -- -e matrixdb.age -i /root/.ssh/agenix/agenix-secret-keys

  echo -n $(cat /var/lib/secrets/turn) | EDITOR='cp /dev/stdin' nix run github:ryantm/agenix -- -e turn.age -i /root/.ssh/agenix/agenix-secret-keys

  echo -n $(cat /var/lib/secrets/matrix_reg_secret) | EDITOR='cp /dev/stdin' nix run github:ryantm/agenix -- -e matrix_reg_secret.age -i /root/.ssh/agenix/agenix-secret-keys

popd

#

nixos-rebuild switch --impure

#

chown root:root /var/lib/secrets/main -R

chown root:root /var/lib/secrets/external_ip -R

chown matrix-synapse:matrix-synapse /var/lib/secrets/matrix_reg_secret -R

chown matrix-synapse:matrix-synapse /var/lib/secrets/matrixdb -R

chown postgres:postgres /var/lib/secrets/nextclouddb -R

chown turnserver:turnserver /var/lib/secrets/turn -R

chown mysql:mysql /var/lib/secrets/wordpressdb -R

chown vaultwarden:vaultwarden /var/lib/secrets/vaultwarden -R

chown onlyoffice:onlyoffice /var/lib/secrets/onlyofficejwtSecretFile

chmod 770 /var/lib/secrets/ -R

#

echo -e "${GREEN}What is your New Matrix (Element Chat) domain name?${ENDCOLOR}"
read 
echo -n $REPLY > /var/lib/domains/matrix

echo -e "${GREEN}What is your New Wordpress domain name?${ENDCOLOR}"
read 
echo -n $REPLY > /var/lib/domains/wordpress

echo -e "${GREEN}What is your New Nextcloud domain name?${ENDCOLOR}"
read 
echo -n $REPLY > /var/lib/domains/nextcloud

echo -e "${GREEN}What is your New BTCPayserver domain name?${ENDCOLOR}"
read 
echo -n $REPLY > /var/lib/domains/btcpayserver

echo -e "${GREEN}What is your New Vaultwarden domain name?${ENDCOLOR}"
read 
echo -n $REPLY > /var/lib/domains/vaultwarden

echo -e "${GREEN}What is your New OnlyOffice domain name?${ENDCOLOR}"
read 
echo -n $REPLY > /var/lib/domains/onlyoffice

echo -e "${GREEN}What is the email you would like to use to manage the SSL certificates for your domains?${ENDCOLOR}"
read 
echo -n $REPLY > /var/lib/domains/sslemail


chown caddy:php /var/lib/domains -R

chmod 770 /var/lib/domains -R

#

set -x


rm -rf /home/free/.config/BraveSoftware

rm -rf /home/free/.local/share/fish/fish_history

#

rm -rf /var/lib/www/wordpress/wp-config.php

rm -rf /var/lib/www/nextcloud/config/config.php

touch /var/lib/www/nextcloud/config/CAN_INSTALL


chown caddy:php /var/lib/www -R

chmod 770 /var/lib/www -R

#

mkdir /var/lib/nextcloud

chown caddy:php /var/lib/nextcloud -R

chmod 770 /var/lib/nextcloud -R

#

mkdir /var/lib/coturn

chown turnserver:turnserver /var/lib/coturn -R

chmod 770 /var/lib/coturn -R

#

echo "root:$(cat /var/lib/secrets/main)" | chpasswd -c SHA512

#

sudo -u free flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak update

#

sudo -u free ssh-keygen -q -N "gosovransytems" -t ed25519 -f /home/free/.ssh/factory_login

sed -i -e "0,/ssh-ed25519.*/{ s::$(cat /home/free/.ssh/factory_login.pub): }" /root/.ssh/authorized_keys

#

echo "free:a" | chpasswd -c SHA512

#

rm -rf /root/sp

rm -rf /root/factory_login_install

rm -rf /home/free/.ssh/sovranpro_login

rm -rf /home/free/.ssh/sovranpro_login.pub


chown bitcoin:bitcoin /run/media/Second_Drive/BTCEcoandBackup/Bitcoin_Node -R

chmod 770 /run/media/Second_Drive/BTCEcoandBackup/Bitcoin_Node -R

chown electrs:electrs /run/media/Second_Drive/BTCEcoandBackup/Electrs_Data -R

chmod 770 /run/media/Second_Drive/BTCEcoandBackup/Electrs_Data -R

nixos-rebuild switch --impure


#

set +x

echo -e "${GREEN}These four passwords are generated for convenience to use for the Web front end setup UI accounts for Nextcloud, Wordpress, VaultWarden, and BTCPayserver (if you want to use them).${ENDCOLOR} \n"

echo -e "$(pwgen -s 17 -1) \n"
echo -e "$(pwgen -s 17 -1) \n"
echo -e "$(pwgen -s 17 -1) \n"
echo -e "$(pwgen -s 17 -1) \n"

#

echo -e "${LIGHTBLUE}One last thing, you need to put the Njalla DDNS info from Njalla into njalla.sh.${ENDCOLOR} \n"

echo -e "${GREEN}All Finished! Please Reboot then Enjoy your New Sovran Pro!${ENDCOLOR} \n"
